import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideNavBar from "./components/SideNavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={inter.className}>
      <SideNavBar /> {/* Include sidebar here */}
      <main style={{ marginLeft: "240px", padding: "20px" }}>
        {/* Content wrapped in main tag */}
        {children}
      </main>
    </body>
  </html>
  );
}
